image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --tag registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA --tag registry.gitlab.com/$CI_PROJECT_PATH:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest

