image: docker:stable

stages:
  - build
  - trigger_runtime
#  - trigger_dockerhub

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
  - apk add curl
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest
    - docker tag $CONTAINER_IMAGE:latest reclaimid/gnunet-docker:latest
    - docker login -u schanzen -p $DOCKERHUB_PUSH_TOKEN
    - docker push reclaimid/gnunet-docker:latest
