image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  VERSION: v0.11.3

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --build-arg version=$VERSION  --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest .
    - docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:$VERSION
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$VERSION

